### ISSUE TITLE
Terminado?

### ISSUE THREAD

**Issue by pxmpxmpurin** [ULL-ESIT-DMSI-1920/vuejs-github-profile-card-antonella-garcia-alu0101227610#1]

**Comment by crguezl** [comment]
@alu0101227610

Buenos días. 

¿Podrías hacer un despliegue en GitHub pages del repo y poner el enlace en el **about** del repo?

Settings --> Pages -> Eliges desde la rama `main`y compruebas que se ve bien.

**Comment by crguezl** [comment]
APTO @alu0101227610
